server:
  port: 8080
zuul:
  ignoredServices: '*'
  prefix: /openlibrary
  routes:
    books:
      path: /books/**
      service-id: book-manager
      strip-prefix: false
    ratings:
      path: /ratings/**
      service-id: book-rating
      strip-prefix: false

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    